GET http://localhost:3000/api/wilder

###

POST http://localhost:3000/api/wilder
Content-Type: application/json

{
  "name": "Jean-Luc Picard"
}

###

PUT http://localhost:3000/api/wilder/11
Content-Type: application/json

{
  "name": "Marie-Hermine Schneider"
}

###

DELETE http://localhost:3000/api/wilder/13
Content-Type: application/json