GET http://localhost:5000/api/wilder

###

POST http://localhost:5000/api/wilder
Content-Type: application/json

{
  "name": "Nyota Uhura",
  "email": "n.uhura@federation.com",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
}

###

POST http://localhost:5000/api/wilder/6/skill/3
Content-Type: application/json

{
  "name": "Another Wilder"
}

###



PUT http://localhost:5000/api/wilder/1
Content-Type: application/json

{
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
}

###

DELETE http://localhost:5000/api/wilder/6
